inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '**/tmp/**/*'
    - '**/script/**/*'
  UseCache: true
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'api/endpoints/**/*'

Metrics/LineLength:
  Max: 120
