files:
  excluded:
    - lib/starter/builder/templates/endpoints.rb
    - lib/starter/builder/templates/files.rb
    - lib/starter/builder/templates/sequel.rb
    - lib/starter/builder/names.rb
    - lib/starter/rake/grape_tasks.rb
    - template
