inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '**/bin/**/*'
    - '**/tmp/**/*'
    - '**/script/**/*'
    # - '**/template/**/*'
    - '**/template/api/**'
    - grape-starter.gemspec
  UseCache: true
  TargetRubyVersion: 2.7

Layout/IndentationWidth:
  Exclude:
    - 'lib/starter/builder/templates/files.rb'
    - 'lib/starter/builder/templates/endpoints.rb'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Naming/AccessorMethodName:
  Exclude:
    - 'lib/starter/builder/templates/files.rb'
    - 'lib/starter/builder/templates/endpoints.rb'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'template/**/*'
    - 'lib/**/*'
    - 'spec/**/*'
