inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '**/bin/**/*'
    - '**/tmp/**/*'
    - '**/script/**/*'
    - '**/template/**/*'
    - grape-starter.gemspec
  UseCache: true
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Style/AccessorMethodName:
  Exclude:
    - 'lib/starter/builder/template_files.rb'
    - 'lib/starter/builder/template_endpoints.rb'

Style/AsciiComments:
  Enabled: false

Style/IndentationWidth:
  Exclude:
    - 'lib/starter/builder/template_files.rb'
    - 'lib/starter/builder/template_endpoints.rb'

Style/Documentation:
  Exclude:
    - 'template/**/*'
    - 'lib/**/*'
    - 'spec/**/*'
