language: ruby

sudo: false

before_install:
  - gem install bundler

rvm:
  - ruby-head
  - 2.7.0-preview3
  - 2.6.5
  - 2.5.7

matrix:
  fast_finish: true

  allow_failures:
    - rvm:
      - ruby-head
      - 2.7.0-preview3
