language: ruby

sudo: false

before_install:
  - gem install bundler

rvm:
  - ruby-head
  - 2.6.1
  - 2.5.3
  - 2.4.5

matrix:
  fast_finish: true

  allow_failures:
    - rvm: ruby-head
    - rvm: 2.4.5
