language: ruby

sudo: false

before_install:
  - gem install bundler

bundler_args: --without development

matrix:
  include:
    - rvm: 2.4.0
    - rvm: 2.3.3
    - rvm: 2.2.6
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
