language: ruby

sudo: false

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.5.0
  - 2.4.3
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
