language: ruby

sudo: false

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.4.2
  - 2.3.5
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
