language: ruby

sudo: false
before_install:
  - gem install bundler

matrix:
  include:
    - rvm: 2.4.0-rc1
    - rvm: 2.3.3
    - rvm: 2.2.6
    - rvm: ruby-head
    - rvm: jruby-9.1.6.0
    - rvm: jruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.6.0
    - rvm: jruby-head
