language: ruby
os: linux
sudo: false

before_install:
  - gem install bundler

rvm:
  - ruby-head
  - 2.7.2
  - 2.6.6
  - 2.5.8

jobs:
  fast_finish: true
  include:
    - rvm: truffleruby-head
      env:
      script: bundle exec rake spec

  allow_failures:
    - rvm: 3.0.0-preview1
    - rvm: ruby-head
    - rvm: truffleruby-head
